require 'faraday'
require 'egauge/version'
require 'egauge/configuration'
require 'faraday_middleware'
require 'json'
require 'egauge/constants'
require 'egauge/register'
require 'egauge/client'
require 'egauge/history'

